Capstone menu
firstpj/capstone-project pull request #1
Opened 2023-04-28 00:03 UTC by firstpj

This pull request is for HTML, CSS, and javascript capstone project.
It is created for an international conference event.

2023-04-28 01:01 UTC, codecaiine requested changes
Hi @firstpj , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good project implementation :heavy_check_mark: 
- No linters errors :heavy_check_mark: 
- Good use of github flow :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 01:01 UTC, codecaiine commented on index.html
> +    </header>
- [ ] Good job so far :clap:  but Please make sure that your Navigation  has the same design as on the original design navigation also your home and about menus need to have the same menu item design :+1:   

#### Original 
![review3](https://user-images.githubusercontent.com/6615394/210884306-9c50363a-4fb8-40c5-af0e-c6e6403b5d42.jpg)

2023-04-28 01:01 UTC, codecaiine commented on index.html
> +    </main>
- [ ] Please make sure that your headline section elements have the same `font size`, `color`, `height`, `width`, and spacing `padding/spacing` as defined in the original design. cause you need to stick the design as much as possible :+1: 

Check the screenshots below to compare and see the differences :point_down: 

####  Original design
![Screenshot from 2022-10-28 17-48-01](https://user-images.githubusercontent.com/6615394/198701404-f4138d1d-135f-4c01-aade-e1994a238fd1.jpg)

2023-04-28 01:01 UTC, codecaiine commented on index.html
> +    </section>
- [ ] Good job so far your contributor section is loading dynamically :clap:  But the design is a bit different compared to the original design. :call_me_hand:   Please make sure that your speaker section has used the same `font`, `height`, `width `, and spacing `padding/margin `. Please change it  to the color defined on the original design  in order to make your  design similar to the original design :+1: 
 Check the screenshots below :point_down:  to see the differences.

#### Orignal design
![Screenshot from 2022-10-28 18-19-46](https://user-images.githubusercontent.com/6615394/198707921-f81e8d82-3ba1-46d2-868b-a34d04408983.jpg)

#### Your design
![Screenshot from 2022-10-28 18-34-01](https://user-images.githubusercontent.com/6615394/198708069-a6800b2a-baa0-416e-bdfb-1764b8874de1.png)

2023-04-28 01:01 UTC, codecaiine commented on index.html
> +    </section>
- [ ] Good job by adding a partner section as required by the previous reviewer but I think you can improve your design because it looks different from the original design. Please make sure to stick to the original design , use , background, and opacity, your logo image also need to have same opacity in order to give a good user experience and make your website great 👍 

#### template
![234959634-e2a93301-ec9f-4521-ac2e-fbb3562620bc](https://user-images.githubusercontent.com/6615394/235008465-6f24398a-0a09-48cc-8116-df503792e87c.png)

2023-04-28 01:01 UTC, codecaiine commented on index.html
> +    </footer>
- [ ] Please make sure that your footer design is similar to the original design. There are a few differences. Please note that it is very important to stick to the original design as much as possible :smile: 

#### The original design
![Screenshot from 2022-10-28 18-41-53](https://user-images.githubusercontent.com/6615394/198709533-f9ce48e0-df96-4c8a-b29b-ffea117dcfcf.jpg)

2023-04-28 01:01 UTC, codecaiine commented on about.html
> +    </section>
- [ ] Your about page design is a bit different from the original design :cry:  You can check the difference with the screenshot I'm sharing with you below :arrow_down:  Please make sure to use the exact same colors, for text, backgrounds, borders, etc, from the original design as required for this project 👍

![Capture](https://user-images.githubusercontent.com/6615394/225180485-0f851d60-585b-4674-89c1-80ffa9b0d4e6.PNG)

2023-04-28 01:01 UTC, codecaiine commented on about.html
> +    </footer>
- [ ] Please make sure that your footer design is similar to the original design. There are a few differences. Please note that it is very important to stick to the original design as much as possible :smile: 

#### The original design
![Screenshot from 2022-10-28 18-41-53](https://user-images.githubusercontent.com/6615394/198709533-f9ce48e0-df96-4c8a-b29b-ffea117dcfcf.jpg)

2023-04-28 01:01 UTC, codecaiine commented on index.html
> +    <section class="program">
- [ ] Please make sure that your program section mobile version design is similar to the original design especially your down button as you can see on the screenshots below :point_down: 

#### Original design
![mobk](https://user-images.githubusercontent.com/6615394/210889991-90c15c91-2920-4058-b09a-95e9944af656.jpg)

2023-04-28 01:01 UTC, codecaiine commented on about.html
> +      </div>
- [ ] Please make sure your about page headline section elements have the same `font size`, `color`, `height`, `width`, and spacing `padding/spacing` as defined in the original design. For example, your headline title needs to be `uppercase`. Please note that is very important to stick to the original design as much as possible :+1: 

Check the screenshots below to compare and see the differences :point_down: 

####  Original design
![Screenshot from 2022-10-28 18-44-06](https://user-images.githubusercontent.com/6615394/198710820-dbee4473-7cbe-49b6-bc50-ab59c70c4a8b.jpg)

2023-04-28 01:01 UTC, codecaiine commented on README.md
> +-[Walkthrough Link](https://https://www.loom.com/share/671307d7da33458da2b8cc6f51252079)
- [ ] The link to your presentation video is broken 😢  Please make sure to fix it also make sure that your video presentation follows the requirement below ⬇️ 

![deo](https://user-images.githubusercontent.com/6615394/235029217-72e82426-ed6d-4df0-b0de-c1d0ba187987.PNG)

2023-04-28 01:01 UTC, codecaiine commented on index.html
> +          <img src="./images/sponsor-2.png" alt="" />
- [ ] I noticed that you added an alt attribute to your image tag that is good but does not leave it empty because it is not good for web accessibility  👍

2023-04-28 16:02 UTC, GedeonTS requested changes
# INVALID REVIEW REQUEST

Hi @firstpj , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
<Img src="https://media.giphy.com/media/11tVh1XRNAunYI/giphy.gif">
## Invalid Code Review Request

You have submitted a PR with failing Linters

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-04-28 17:36 UTC, BertrandConxy requested changes
Hi @firstpj, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights 💪 
- No linter errors
- correct flow is used
- good improvement based on the previous reviewer's suggestions


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 17:36 UTC, BertrandConxy commented on index.html
> +          <img src="./images/gtv.png" alt="" />
- [ ] Good job so far 👏 As suggested by the previous reviewer, please add the alt description text within the `alt` tags for easy accessibility 😃

2023-04-28 17:36 UTC, BertrandConxy commented on README.md
> +-[Walkthrough Link](https://https://www.loom.com/share/671307d7da33458da2b8cc6f51252079)
- [ ] Despite your efforts to implement suggested changes, the above link to the Project presentation is still inaccessible 😢 I would suggest that you check again the link for correctness. If it is correct, that means you have not granted access for it to be accessed or viewed by everyone. That is why I suggest that you can ensure that that access is granted too 😎

2023-04-28 17:36 UTC, BertrandConxy commented on about.html
> +      </section>
- [ ] As previous reviewer suggested, please ensure that your design looks the same as the given design. I appreciate your effort in doing so. In addition to what you have done, I would suggest that you align this contact address in the center as we can see on the design. Please look at the comparison 👇 
Given design
![image](https://user-images.githubusercontent.com/90222110/235215278-1969fc04-62d8-44a0-a056-6b63792827dc.png)

Your design
![image](https://user-images.githubusercontent.com/90222110/235215394-632e15b3-04f1-400f-ad54-c3a0a8909791.png)

2023-04-29 12:13 UTC, PinkMoon25 requested changes
Hi @firstpj , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media2.giphy.com/media/qLWdMYX1NYF2g/giphy-downsized-medium.gif"/>

 ## Highlights
Linter checks :heavy_check_mark: 
github flow :heavy_check_mark: 
Live deploy :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-29 12:13 UTC, PinkMoon25 commented on README.md
> +-[Walkthrough Link](https://https://https://www.loom.com/share/a6cf61fe03ec49d7b36bfeaacece8bac)
- [ ] Good job implementing the changes suggested, however as requested https://github.com/firstpj/capstone-project/pull/1#discussion_r1179836793 you need to fix the broken link of your video presentation in the README , notice how you have multiple https:// in your link. please fix it :+1:

2023-04-29 13:00 UTC, BertrandConxy approved these changes
Hi @firstpj  , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💪 
- No linter errors
- project requirements are met
- project works fine


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-30 11:29 UTC, merged